USE espheras_transcargo;

insert into `places`(`id`,`placeType`,`name`,`address`,`description`,`provincia`) values (1,2,'Puerto Balboa','Panama Ports','Espacio para contenerdores 20"','Panama');
insert into `places`(`id`,`placeType`,`name`,`address`,`description`,`provincia`) values (2,1,'Chilibre''s Warehouse','Chilibre, Panama',null,'Panama');
insert into `places`(`id`,`placeType`,`name`,`address`,`description`,`provincia`) values (3,1,'Puerto Armuelles','Puerto Armuelles',null,'Chiriqui');
insert into `places`(`id`,`placeType`,`name`,`address`,`description`,`provincia`) values (4,2,'Almirante','Bocas del Toro',null,'Bocas del Toro');
insert into `places`(`id`,`placeType`,`name`,`address`,`description`,`provincia`) values (5,2,'Samba Bonita','Colon',null,'Colon');
insert into `places`(`id`,`placeType`,`name`,`address`,`description`,`provincia`) values (6,1,'Coquira','Panama',null,'Panama');
insert into `places`(`id`,`placeType`,`name`,`address`,`description`,`provincia`) values (7,1,'Patio TR2','Panama',null,'Panama');
insert into `places`(`id`,`placeType`,`name`,`address`,`description`,`provincia`) values (8,2,'Puerto Balboa','Panama',null,'Panama');
insert into `places`(`id`,`placeType`,`name`,`address`,`description`,`provincia`) values (9,2,'Puerto Manzanillo','Panama',null,'Panama');
insert into `places`(`id`,`placeType`,`name`,`address`,`description`,`provincia`) values (10,1,'Trailmovil','Panama',null,'Panama');
insert into `places`(`id`,`placeType`,`name`,`address`,`description`,`provincia`) values (11,1,'Pricesmart Dorado','Panama',null,'Panama');
insert into `places`(`id`,`placeType`,`name`,`address`,`description`,`provincia`) values (12,2,'Mañanitas','Panama',null,'Panama');
insert into `places`(`id`,`placeType`,`name`,`address`,`description`,`provincia`) values (13,2,'Puerto de Cristobal','Panama',null,'Panama');
insert into `places`(`id`,`placeType`,`name`,`address`,`description`,`provincia`) values (14,1,'Pricesmart Brisas','Panama',null,'Panama');
insert into `places`(`id`,`placeType`,`name`,`address`,`description`,`provincia`) values (15,1,'Almacenadora Kinte','Panama',null,'Panama');
insert into `places`(`id`,`placeType`,`name`,`address`,`description`,`provincia`) values (16,1,'CDI - Locería','Panama',null,'Panama');
insert into `places`(`id`,`placeType`,`name`,`address`,`description`,`provincia`) values (17,1,'DHL - Parque Sur','Panama',null,'Panama');
insert into `places`(`id`,`placeType`,`name`,`address`,`description`,`provincia`) values (18,2,'Colon Container Term','Panama',null,'Panama');
insert into `places`(`id`,`placeType`,`name`,`address`,`description`,`provincia`) values (19,2,'PSMT DC - Mañanitas','Panama',null,'Panama');
insert into `places`(`id`,`placeType`,`name`,`address`,`description`,`provincia`) values (20,1,'Pricesmart Vía Bras','Panama',null,'Panama');
insert into `places`(`id`,`placeType`,`name`,`address`,`description`,`provincia`) values (21,1,'Pricesmart David','Panama',null,'Panama');
insert into `places`(`id`,`placeType`,`name`,`address`,`description`,`provincia`) values (22,1,'Feduro - Milla 8','Panama',null,'Panama');
insert into `places`(`id`,`placeType`,`name`,`address`,`description`,`provincia`) values (23,1,'Patio TR2-1','Panama',null,'Panama');
insert into `places`(`id`,`placeType`,`name`,`address`,`description`,`provincia`) values (24,1,'David','Panama',null,'Panama');
insert into `places`(`id`,`placeType`,`name`,`address`,`description`,`provincia`) values (25,1,'Llano Bonito','Panama',null,'Panama');
insert into `places`(`id`,`placeType`,`name`,`address`,`description`,`provincia`) values (26,1,'Galores - Mañanitas','Mañanitas',null,'Panama');
insert into `places`(`id`,`placeType`,`name`,`address`,`description`,`provincia`) values (27,1,'Ciudad de Panamá','Panama',null,'Panama');
insert into `places`(`id`,`placeType`,`name`,`address`,`description`,`provincia`) values (29,1,'Curundú Industrial','Panama',null,'Panama');
insert into `places`(`id`,`placeType`,`name`,`address`,`description`,`provincia`) values (30,1,'Intertrade','Panama',null,'Panama');
